"""add is_adjustment field to transactions

Revision ID: fbfde5fb6f92
Revises: ce66080e9e32
Create Date: 2025-11-19 12:48:41.472185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfde5fb6f92'
down_revision: Union[str, None] = 'ce66080e9e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_adjustment', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_adjustment')
    # ### end Alembic commands ###
