"""add_accounts_tags_and_transaction_tags_tables

Revision ID: ce66080e9e32
Revises: cd12f1e07ac8
Create Date: 2025-11-19 11:26:11.499568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce66080e9e32'
down_revision: Union[str, None] = 'cd12f1e07ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create accounts table
    op.create_table(
        'accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('initial_balance', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('initial_balance_date', sa.Date(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='JPY'),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.CheckConstraint("type IN ('bank', 'cash', 'credit_card', 'investment', 'receivable', 'other')", name='valid_account_type'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.create_index('ix_accounts_type_active', 'accounts', ['type', 'is_active'], unique=False)

    # Create tags table
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)

    # Create transaction_tags junction table
    op.create_table(
        'transaction_tags',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )

    # Fix exchange_rates index (existing issue)
    op.drop_index(op.f('ix_exchange_rates_currency'), table_name='exchange_rates')

    # Add account_id to transactions table
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse account_id changes from transactions table
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_column('transactions', 'account_id')

    # Restore exchange_rates index
    op.create_index(op.f('ix_exchange_rates_currency'), 'exchange_rates', ['currency'], unique=1)

    # Drop transaction_tags junction table
    op.drop_table('transaction_tags')

    # Drop tags table
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')

    # Drop accounts table
    op.drop_index('ix_accounts_type_active', table_name='accounts')
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
