/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RelocationRouteImport } from './routes/relocation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ProxyRouteImport } from './routes/proxy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const ProfileLazyRouteImport = createFileRoute('/profile')()
const GamificationLazyRouteImport = createFileRoute('/gamification')()

const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const GamificationLazyRoute = GamificationLazyRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/gamification.lazy').then((d) => d.Route))
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/upload.lazy').then((d) => d.Route))
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transactions.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/report.lazy').then((d) => d.Route))
const RelocationRoute = RelocationRouteImport.update({
  id: '/relocation',
  path: '/relocation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/relocation.lazy').then((d) => d.Route))
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recurring.lazy').then((d) => d.Route))
const ProxyRoute = ProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/proxy.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/goals.lazy').then((d) => d.Route))
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/budget.lazy').then((d) => d.Route))
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/accounts.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/goals': typeof GoalsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/proxy': typeof ProxyRoute
  '/recurring': typeof RecurringRoute
  '/register': typeof RegisterRoute
  '/relocation': typeof RelocationRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/upload': typeof UploadRoute
  '/gamification': typeof GamificationLazyRoute
  '/profile': typeof ProfileLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/goals': typeof GoalsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/proxy': typeof ProxyRoute
  '/recurring': typeof RecurringRoute
  '/register': typeof RegisterRoute
  '/relocation': typeof RelocationRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/upload': typeof UploadRoute
  '/gamification': typeof GamificationLazyRoute
  '/profile': typeof ProfileLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/goals': typeof GoalsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/proxy': typeof ProxyRoute
  '/recurring': typeof RecurringRoute
  '/register': typeof RegisterRoute
  '/relocation': typeof RelocationRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/upload': typeof UploadRoute
  '/gamification': typeof GamificationLazyRoute
  '/profile': typeof ProfileLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/budget'
    | '/goals'
    | '/landing'
    | '/login'
    | '/proxy'
    | '/recurring'
    | '/register'
    | '/relocation'
    | '/report'
    | '/settings'
    | '/transactions'
    | '/upload'
    | '/gamification'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/budget'
    | '/goals'
    | '/landing'
    | '/login'
    | '/proxy'
    | '/recurring'
    | '/register'
    | '/relocation'
    | '/report'
    | '/settings'
    | '/transactions'
    | '/upload'
    | '/gamification'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/analytics'
    | '/budget'
    | '/goals'
    | '/landing'
    | '/login'
    | '/proxy'
    | '/recurring'
    | '/register'
    | '/relocation'
    | '/report'
    | '/settings'
    | '/transactions'
    | '/upload'
    | '/gamification'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BudgetRoute: typeof BudgetRoute
  GoalsRoute: typeof GoalsRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ProxyRoute: typeof ProxyRoute
  RecurringRoute: typeof RecurringRoute
  RegisterRoute: typeof RegisterRoute
  RelocationRoute: typeof RelocationRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  UploadRoute: typeof UploadRoute
  GamificationLazyRoute: typeof GamificationLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification': {
      id: '/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof GamificationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relocation': {
      id: '/relocation'
      path: '/relocation'
      fullPath: '/relocation'
      preLoaderRoute: typeof RelocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy': {
      id: '/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BudgetRoute: BudgetRoute,
  GoalsRoute: GoalsRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ProxyRoute: ProxyRoute,
  RecurringRoute: RecurringRoute,
  RegisterRoute: RegisterRoute,
  RelocationRoute: RelocationRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  UploadRoute: UploadRoute,
  GamificationLazyRoute: GamificationLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
